version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: poll_live
      POSTGRES_USER: polluser
      POSTGRES_PASSWORD: pollpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data


  desktop-app:
    build: ./desktop
    # Опционально: можно собирать как отдельный образ

  kibana:
    image: kibana:8.7.0
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://polluser:pollpass@db:5432/poll_live
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - db
      - redis
      - rabbitmq
      - elasticsearch

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  celery-worker:
    build: ./backend
    command: celery -A workers.celery_app worker -l info
    depends_on:
      - rabbitmq
      - redis
      - backend

volumes:
  pgdata:
  esdata:

