version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: test_poll_live
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+asyncpg://testuser:testpass@db:5432/test_poll_live
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
